apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone
  region: us-west-1

nodeGroups:
  - name: ng-1
    instanceType: t2.medium
    desiredCapacity: 2
    volumeSize: 10
    ssh:
      allow: false
